/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.unipotsdam.elis.portfolio.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import de.unipotsdam.elis.portfolio.service.persistence.PortfolioPermissionPK;

import java.io.Serializable;

/**
 * The base model interface for the PortfolioPermission service. Represents a row in the &quot;Portfolio_PortfolioPermission&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.unipotsdam.elis.portfolio.model.impl.PortfolioPermissionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.unipotsdam.elis.portfolio.model.impl.PortfolioPermissionImpl}.
 * </p>
 *
 * @author Matthias
 * @see PortfolioPermission
 * @see de.unipotsdam.elis.portfolio.model.impl.PortfolioPermissionImpl
 * @see de.unipotsdam.elis.portfolio.model.impl.PortfolioPermissionModelImpl
 * @generated
 */
public interface PortfolioPermissionModel extends BaseModel<PortfolioPermission> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a portfolio permission model instance should use the {@link PortfolioPermission} interface instead.
	 */

	/**
	 * Returns the primary key of this portfolio permission.
	 *
	 * @return the primary key of this portfolio permission
	 */
	public PortfolioPermissionPK getPrimaryKey();

	/**
	 * Sets the primary key of this portfolio permission.
	 *
	 * @param primaryKey the primary key of this portfolio permission
	 */
	public void setPrimaryKey(PortfolioPermissionPK primaryKey);

	/**
	 * Returns the plid of this portfolio permission.
	 *
	 * @return the plid of this portfolio permission
	 */
	public long getPlid();

	/**
	 * Sets the plid of this portfolio permission.
	 *
	 * @param plid the plid of this portfolio permission
	 */
	public void setPlid(long plid);

	/**
	 * Returns the user ID of this portfolio permission.
	 *
	 * @return the user ID of this portfolio permission
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this portfolio permission.
	 *
	 * @param userId the user ID of this portfolio permission
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this portfolio permission.
	 *
	 * @return the user uuid of this portfolio permission
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this portfolio permission.
	 *
	 * @param userUuid the user uuid of this portfolio permission
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		de.unipotsdam.elis.portfolio.model.PortfolioPermission portfolioPermission);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.unipotsdam.elis.portfolio.model.PortfolioPermission> toCacheModel();

	@Override
	public de.unipotsdam.elis.portfolio.model.PortfolioPermission toEscapedModel();

	@Override
	public de.unipotsdam.elis.portfolio.model.PortfolioPermission toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}