/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.unipotsdam.elis.portfolio.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import de.unipotsdam.elis.portfolio.service.persistence.PortfolioFeedbackPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PortfolioFeedback service. Represents a row in the &quot;Portfolio_PortfolioFeedback&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.unipotsdam.elis.portfolio.model.impl.PortfolioFeedbackModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.unipotsdam.elis.portfolio.model.impl.PortfolioFeedbackImpl}.
 * </p>
 *
 * @author Matthias
 * @see PortfolioFeedback
 * @see de.unipotsdam.elis.portfolio.model.impl.PortfolioFeedbackImpl
 * @see de.unipotsdam.elis.portfolio.model.impl.PortfolioFeedbackModelImpl
 * @generated
 */
public interface PortfolioFeedbackModel extends BaseModel<PortfolioFeedback> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a portfolio feedback model instance should use the {@link PortfolioFeedback} interface instead.
	 */

	/**
	 * Returns the primary key of this portfolio feedback.
	 *
	 * @return the primary key of this portfolio feedback
	 */
	public PortfolioFeedbackPK getPrimaryKey();

	/**
	 * Sets the primary key of this portfolio feedback.
	 *
	 * @param primaryKey the primary key of this portfolio feedback
	 */
	public void setPrimaryKey(PortfolioFeedbackPK primaryKey);

	/**
	 * Returns the plid of this portfolio feedback.
	 *
	 * @return the plid of this portfolio feedback
	 */
	public long getPlid();

	/**
	 * Sets the plid of this portfolio feedback.
	 *
	 * @param plid the plid of this portfolio feedback
	 */
	public void setPlid(long plid);

	/**
	 * Returns the user ID of this portfolio feedback.
	 *
	 * @return the user ID of this portfolio feedback
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this portfolio feedback.
	 *
	 * @param userId the user ID of this portfolio feedback
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this portfolio feedback.
	 *
	 * @return the user uuid of this portfolio feedback
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this portfolio feedback.
	 *
	 * @param userUuid the user uuid of this portfolio feedback
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the feedback status of this portfolio feedback.
	 *
	 * @return the feedback status of this portfolio feedback
	 */
	public int getFeedbackStatus();

	/**
	 * Sets the feedback status of this portfolio feedback.
	 *
	 * @param feedbackStatus the feedback status of this portfolio feedback
	 */
	public void setFeedbackStatus(int feedbackStatus);

	/**
	 * Returns the create date of this portfolio feedback.
	 *
	 * @return the create date of this portfolio feedback
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this portfolio feedback.
	 *
	 * @param createDate the create date of this portfolio feedback
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this portfolio feedback.
	 *
	 * @return the modified date of this portfolio feedback
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this portfolio feedback.
	 *
	 * @param modifiedDate the modified date of this portfolio feedback
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		de.unipotsdam.elis.portfolio.model.PortfolioFeedback portfolioFeedback);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.unipotsdam.elis.portfolio.model.PortfolioFeedback> toCacheModel();

	@Override
	public de.unipotsdam.elis.portfolio.model.PortfolioFeedback toEscapedModel();

	@Override
	public de.unipotsdam.elis.portfolio.model.PortfolioFeedback toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}