/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.unipotsdam.elis.owncloud.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import de.unipotsdam.elis.owncloud.service.persistence.CustomSiteRootFolderPK;

import java.io.Serializable;

/**
 * The base model interface for the CustomSiteRootFolder service. Represents a row in the &quot;Owncloud_CustomSiteRootFolder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.unipotsdam.elis.owncloud.model.impl.CustomSiteRootFolderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.unipotsdam.elis.owncloud.model.impl.CustomSiteRootFolderImpl}.
 * </p>
 *
 * @author Matthias
 * @see CustomSiteRootFolder
 * @see de.unipotsdam.elis.owncloud.model.impl.CustomSiteRootFolderImpl
 * @see de.unipotsdam.elis.owncloud.model.impl.CustomSiteRootFolderModelImpl
 * @generated
 */
public interface CustomSiteRootFolderModel extends BaseModel<CustomSiteRootFolder> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a custom site root folder model instance should use the {@link CustomSiteRootFolder} interface instead.
	 */

	/**
	 * Returns the primary key of this custom site root folder.
	 *
	 * @return the primary key of this custom site root folder
	 */
	public CustomSiteRootFolderPK getPrimaryKey();

	/**
	 * Sets the primary key of this custom site root folder.
	 *
	 * @param primaryKey the primary key of this custom site root folder
	 */
	public void setPrimaryKey(CustomSiteRootFolderPK primaryKey);

	/**
	 * Returns the user ID of this custom site root folder.
	 *
	 * @return the user ID of this custom site root folder
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this custom site root folder.
	 *
	 * @param userId the user ID of this custom site root folder
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this custom site root folder.
	 *
	 * @return the user uuid of this custom site root folder
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this custom site root folder.
	 *
	 * @param userUuid the user uuid of this custom site root folder
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the original path of this custom site root folder.
	 *
	 * @return the original path of this custom site root folder
	 */
	@AutoEscape
	public String getOriginalPath();

	/**
	 * Sets the original path of this custom site root folder.
	 *
	 * @param originalPath the original path of this custom site root folder
	 */
	public void setOriginalPath(String originalPath);

	/**
	 * Returns the custom path of this custom site root folder.
	 *
	 * @return the custom path of this custom site root folder
	 */
	@AutoEscape
	public String getCustomPath();

	/**
	 * Sets the custom path of this custom site root folder.
	 *
	 * @param customPath the custom path of this custom site root folder
	 */
	public void setCustomPath(String customPath);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		de.unipotsdam.elis.owncloud.model.CustomSiteRootFolder customSiteRootFolder);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.unipotsdam.elis.owncloud.model.CustomSiteRootFolder> toCacheModel();

	@Override
	public de.unipotsdam.elis.owncloud.model.CustomSiteRootFolder toEscapedModel();

	@Override
	public de.unipotsdam.elis.owncloud.model.CustomSiteRootFolder toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}