/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.unipotsdam.elis.portfolio.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.util.PortalUtil;

import de.unipotsdam.elis.portfolio.model.PortfolioFeedback;
import de.unipotsdam.elis.portfolio.model.PortfolioFeedbackModel;
import de.unipotsdam.elis.portfolio.model.PortfolioFeedbackSoap;
import de.unipotsdam.elis.portfolio.service.persistence.PortfolioFeedbackPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the PortfolioFeedback service. Represents a row in the &quot;Portfolio_PortfolioFeedback&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link de.unipotsdam.elis.portfolio.model.PortfolioFeedbackModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PortfolioFeedbackImpl}.
 * </p>
 *
 * @author Matthias
 * @see PortfolioFeedbackImpl
 * @see de.unipotsdam.elis.portfolio.model.PortfolioFeedback
 * @see de.unipotsdam.elis.portfolio.model.PortfolioFeedbackModel
 * @generated
 */
@JSON(strict = true)
public class PortfolioFeedbackModelImpl extends BaseModelImpl<PortfolioFeedback>
	implements PortfolioFeedbackModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a portfolio feedback model instance should use the {@link de.unipotsdam.elis.portfolio.model.PortfolioFeedback} interface instead.
	 */
	public static final String TABLE_NAME = "Portfolio_PortfolioFeedback";
	public static final Object[][] TABLE_COLUMNS = {
			{ "plid", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "feedbackStatus", Types.INTEGER },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table Portfolio_PortfolioFeedback (plid LONG not null,userId LONG not null,feedbackStatus INTEGER,createDate DATE null,modifiedDate DATE null,primary key (plid, userId))";
	public static final String TABLE_SQL_DROP = "drop table Portfolio_PortfolioFeedback";
	public static final String ORDER_BY_JPQL = " ORDER BY portfolioFeedback.id.plid ASC, portfolioFeedback.id.userId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Portfolio_PortfolioFeedback.plid ASC, Portfolio_PortfolioFeedback.userId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.de.unipotsdam.elis.portfolio.model.PortfolioFeedback"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.de.unipotsdam.elis.portfolio.model.PortfolioFeedback"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.de.unipotsdam.elis.portfolio.model.PortfolioFeedback"),
			true);
	public static long FEEDBACKSTATUS_COLUMN_BITMASK = 1L;
	public static long PLID_COLUMN_BITMASK = 2L;
	public static long USERID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static PortfolioFeedback toModel(PortfolioFeedbackSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		PortfolioFeedback model = new PortfolioFeedbackImpl();

		model.setPlid(soapModel.getPlid());
		model.setUserId(soapModel.getUserId());
		model.setFeedbackStatus(soapModel.getFeedbackStatus());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<PortfolioFeedback> toModels(
		PortfolioFeedbackSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<PortfolioFeedback> models = new ArrayList<PortfolioFeedback>(soapModels.length);

		for (PortfolioFeedbackSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.de.unipotsdam.elis.portfolio.model.PortfolioFeedback"));

	public PortfolioFeedbackModelImpl() {
	}

	@Override
	public PortfolioFeedbackPK getPrimaryKey() {
		return new PortfolioFeedbackPK(_plid, _userId);
	}

	@Override
	public void setPrimaryKey(PortfolioFeedbackPK primaryKey) {
		setPlid(primaryKey.plid);
		setUserId(primaryKey.userId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new PortfolioFeedbackPK(_plid, _userId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((PortfolioFeedbackPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return PortfolioFeedback.class;
	}

	@Override
	public String getModelClassName() {
		return PortfolioFeedback.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("plid", getPlid());
		attributes.put("userId", getUserId());
		attributes.put("feedbackStatus", getFeedbackStatus());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long plid = (Long)attributes.get("plid");

		if (plid != null) {
			setPlid(plid);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Integer feedbackStatus = (Integer)attributes.get("feedbackStatus");

		if (feedbackStatus != null) {
			setFeedbackStatus(feedbackStatus);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@JSON
	@Override
	public long getPlid() {
		return _plid;
	}

	@Override
	public void setPlid(long plid) {
		_columnBitmask |= PLID_COLUMN_BITMASK;

		if (!_setOriginalPlid) {
			_setOriginalPlid = true;

			_originalPlid = _plid;
		}

		_plid = plid;
	}

	public long getOriginalPlid() {
		return _originalPlid;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public int getFeedbackStatus() {
		return _feedbackStatus;
	}

	@Override
	public void setFeedbackStatus(int feedbackStatus) {
		_columnBitmask |= FEEDBACKSTATUS_COLUMN_BITMASK;

		if (!_setOriginalFeedbackStatus) {
			_setOriginalFeedbackStatus = true;

			_originalFeedbackStatus = _feedbackStatus;
		}

		_feedbackStatus = feedbackStatus;
	}

	public int getOriginalFeedbackStatus() {
		return _originalFeedbackStatus;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public PortfolioFeedback toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PortfolioFeedback)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PortfolioFeedbackImpl portfolioFeedbackImpl = new PortfolioFeedbackImpl();

		portfolioFeedbackImpl.setPlid(getPlid());
		portfolioFeedbackImpl.setUserId(getUserId());
		portfolioFeedbackImpl.setFeedbackStatus(getFeedbackStatus());
		portfolioFeedbackImpl.setCreateDate(getCreateDate());
		portfolioFeedbackImpl.setModifiedDate(getModifiedDate());

		portfolioFeedbackImpl.resetOriginalValues();

		return portfolioFeedbackImpl;
	}

	@Override
	public int compareTo(PortfolioFeedback portfolioFeedback) {
		PortfolioFeedbackPK primaryKey = portfolioFeedback.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PortfolioFeedback)) {
			return false;
		}

		PortfolioFeedback portfolioFeedback = (PortfolioFeedback)obj;

		PortfolioFeedbackPK primaryKey = portfolioFeedback.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		PortfolioFeedbackModelImpl portfolioFeedbackModelImpl = this;

		portfolioFeedbackModelImpl._originalPlid = portfolioFeedbackModelImpl._plid;

		portfolioFeedbackModelImpl._setOriginalPlid = false;

		portfolioFeedbackModelImpl._originalUserId = portfolioFeedbackModelImpl._userId;

		portfolioFeedbackModelImpl._setOriginalUserId = false;

		portfolioFeedbackModelImpl._originalFeedbackStatus = portfolioFeedbackModelImpl._feedbackStatus;

		portfolioFeedbackModelImpl._setOriginalFeedbackStatus = false;

		portfolioFeedbackModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PortfolioFeedback> toCacheModel() {
		PortfolioFeedbackCacheModel portfolioFeedbackCacheModel = new PortfolioFeedbackCacheModel();

		portfolioFeedbackCacheModel.plid = getPlid();

		portfolioFeedbackCacheModel.userId = getUserId();

		portfolioFeedbackCacheModel.feedbackStatus = getFeedbackStatus();

		Date createDate = getCreateDate();

		if (createDate != null) {
			portfolioFeedbackCacheModel.createDate = createDate.getTime();
		}
		else {
			portfolioFeedbackCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			portfolioFeedbackCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			portfolioFeedbackCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return portfolioFeedbackCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{plid=");
		sb.append(getPlid());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", feedbackStatus=");
		sb.append(getFeedbackStatus());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("de.unipotsdam.elis.portfolio.model.PortfolioFeedback");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>plid</column-name><column-value><![CDATA[");
		sb.append(getPlid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>feedbackStatus</column-name><column-value><![CDATA[");
		sb.append(getFeedbackStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PortfolioFeedback.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			PortfolioFeedback.class
		};
	private long _plid;
	private long _originalPlid;
	private boolean _setOriginalPlid;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private int _feedbackStatus;
	private int _originalFeedbackStatus;
	private boolean _setOriginalFeedbackStatus;
	private Date _createDate;
	private Date _modifiedDate;
	private long _columnBitmask;
	private PortfolioFeedback _escapedModel;
}