/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.unipotsdam.elis.activities.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the MoodleSocialActivity service. Represents a row in the &quot;Activity_MoodleSocialActivity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.unipotsdam.elis.activities.model.impl.MoodleSocialActivityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.unipotsdam.elis.activities.model.impl.MoodleSocialActivityImpl}.
 * </p>
 *
 * @author Matthias
 * @see MoodleSocialActivity
 * @see de.unipotsdam.elis.activities.model.impl.MoodleSocialActivityImpl
 * @see de.unipotsdam.elis.activities.model.impl.MoodleSocialActivityModelImpl
 * @generated
 */
public interface MoodleSocialActivityModel extends BaseModel<MoodleSocialActivity> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a moodle social activity model instance should use the {@link MoodleSocialActivity} interface instead.
	 */

	/**
	 * Returns the primary key of this moodle social activity.
	 *
	 * @return the primary key of this moodle social activity
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this moodle social activity.
	 *
	 * @param primaryKey the primary key of this moodle social activity
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ext social activity ID of this moodle social activity.
	 *
	 * @return the ext social activity ID of this moodle social activity
	 */
	public long getExtSocialActivityId();

	/**
	 * Sets the ext social activity ID of this moodle social activity.
	 *
	 * @param extSocialActivityId the ext social activity ID of this moodle social activity
	 */
	public void setExtSocialActivityId(long extSocialActivityId);

	/**
	 * Returns the user ID of this moodle social activity.
	 *
	 * @return the user ID of this moodle social activity
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this moodle social activity.
	 *
	 * @param userId the user ID of this moodle social activity
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this moodle social activity.
	 *
	 * @return the user uuid of this moodle social activity
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this moodle social activity.
	 *
	 * @param userUuid the user uuid of this moodle social activity
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the type of this moodle social activity.
	 *
	 * @return the type of this moodle social activity
	 */
	public int getType();

	/**
	 * Sets the type of this moodle social activity.
	 *
	 * @param type the type of this moodle social activity
	 */
	public void setType(int type);

	/**
	 * Returns the ext service activity type of this moodle social activity.
	 *
	 * @return the ext service activity type of this moodle social activity
	 */
	@AutoEscape
	public String getExtServiceActivityType();

	/**
	 * Sets the ext service activity type of this moodle social activity.
	 *
	 * @param extServiceActivityType the ext service activity type of this moodle social activity
	 */
	public void setExtServiceActivityType(String extServiceActivityType);

	/**
	 * Returns the ext service context of this moodle social activity.
	 *
	 * @return the ext service context of this moodle social activity
	 */
	@AutoEscape
	public String getExtServiceContext();

	/**
	 * Sets the ext service context of this moodle social activity.
	 *
	 * @param extServiceContext the ext service context of this moodle social activity
	 */
	public void setExtServiceContext(String extServiceContext);

	/**
	 * Returns the data of this moodle social activity.
	 *
	 * @return the data of this moodle social activity
	 */
	@AutoEscape
	public String getData();

	/**
	 * Sets the data of this moodle social activity.
	 *
	 * @param data the data of this moodle social activity
	 */
	public void setData(String data);

	/**
	 * Returns the published of this moodle social activity.
	 *
	 * @return the published of this moodle social activity
	 */
	public long getPublished();

	/**
	 * Sets the published of this moodle social activity.
	 *
	 * @param published the published of this moodle social activity
	 */
	public void setPublished(long published);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		de.unipotsdam.elis.activities.model.MoodleSocialActivity moodleSocialActivity);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.unipotsdam.elis.activities.model.MoodleSocialActivity> toCacheModel();

	@Override
	public de.unipotsdam.elis.activities.model.MoodleSocialActivity toEscapedModel();

	@Override
	public de.unipotsdam.elis.activities.model.MoodleSocialActivity toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}