/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.unipotsdam.elis.custompages.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import de.unipotsdam.elis.custompages.service.persistence.CustomPageFeedbackPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CustomPageFeedback service. Represents a row in the &quot;CustomPages_CustomPageFeedback&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.unipotsdam.elis.custompages.model.impl.CustomPageFeedbackModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.unipotsdam.elis.custompages.model.impl.CustomPageFeedbackImpl}.
 * </p>
 *
 * @author Matthias
 * @see CustomPageFeedback
 * @see de.unipotsdam.elis.custompages.model.impl.CustomPageFeedbackImpl
 * @see de.unipotsdam.elis.custompages.model.impl.CustomPageFeedbackModelImpl
 * @generated
 */
public interface CustomPageFeedbackModel extends BaseModel<CustomPageFeedback> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a custom page feedback model instance should use the {@link CustomPageFeedback} interface instead.
	 */

	/**
	 * Returns the primary key of this custom page feedback.
	 *
	 * @return the primary key of this custom page feedback
	 */
	public CustomPageFeedbackPK getPrimaryKey();

	/**
	 * Sets the primary key of this custom page feedback.
	 *
	 * @param primaryKey the primary key of this custom page feedback
	 */
	public void setPrimaryKey(CustomPageFeedbackPK primaryKey);

	/**
	 * Returns the plid of this custom page feedback.
	 *
	 * @return the plid of this custom page feedback
	 */
	public long getPlid();

	/**
	 * Sets the plid of this custom page feedback.
	 *
	 * @param plid the plid of this custom page feedback
	 */
	public void setPlid(long plid);

	/**
	 * Returns the user ID of this custom page feedback.
	 *
	 * @return the user ID of this custom page feedback
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this custom page feedback.
	 *
	 * @param userId the user ID of this custom page feedback
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this custom page feedback.
	 *
	 * @return the user uuid of this custom page feedback
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this custom page feedback.
	 *
	 * @param userUuid the user uuid of this custom page feedback
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the feedback status of this custom page feedback.
	 *
	 * @return the feedback status of this custom page feedback
	 */
	public int getFeedbackStatus();

	/**
	 * Sets the feedback status of this custom page feedback.
	 *
	 * @param feedbackStatus the feedback status of this custom page feedback
	 */
	public void setFeedbackStatus(int feedbackStatus);

	/**
	 * Returns the hidden of this custom page feedback.
	 *
	 * @return the hidden of this custom page feedback
	 */
	public boolean getHidden();

	/**
	 * Returns <code>true</code> if this custom page feedback is hidden.
	 *
	 * @return <code>true</code> if this custom page feedback is hidden; <code>false</code> otherwise
	 */
	public boolean isHidden();

	/**
	 * Sets whether this custom page feedback is hidden.
	 *
	 * @param hidden the hidden of this custom page feedback
	 */
	public void setHidden(boolean hidden);

	/**
	 * Returns the create date of this custom page feedback.
	 *
	 * @return the create date of this custom page feedback
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this custom page feedback.
	 *
	 * @param createDate the create date of this custom page feedback
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this custom page feedback.
	 *
	 * @return the modified date of this custom page feedback
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this custom page feedback.
	 *
	 * @param modifiedDate the modified date of this custom page feedback
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		de.unipotsdam.elis.custompages.model.CustomPageFeedback customPageFeedback);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.unipotsdam.elis.custompages.model.CustomPageFeedback> toCacheModel();

	@Override
	public de.unipotsdam.elis.custompages.model.CustomPageFeedback toEscapedModel();

	@Override
	public de.unipotsdam.elis.custompages.model.CustomPageFeedback toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}