/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.unipotsdam.elis.language.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LanguageKey service. Represents a row in the &quot;Language_LanguageKey&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.unipotsdam.elis.language.model.impl.LanguageKeyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.unipotsdam.elis.language.model.impl.LanguageKeyImpl}.
 * </p>
 *
 * @author Matthias
 * @see LanguageKey
 * @see de.unipotsdam.elis.language.model.impl.LanguageKeyImpl
 * @see de.unipotsdam.elis.language.model.impl.LanguageKeyModelImpl
 * @generated
 */
public interface LanguageKeyModel extends BaseModel<LanguageKey> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a language key model instance should use the {@link LanguageKey} interface instead.
	 */

	/**
	 * Returns the primary key of this language key.
	 *
	 * @return the primary key of this language key
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this language key.
	 *
	 * @param primaryKey the primary key of this language key
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the key of this language key.
	 *
	 * @return the key of this language key
	 */
	@AutoEscape
	public String getKey();

	/**
	 * Sets the key of this language key.
	 *
	 * @param key the key of this language key
	 */
	public void setKey(String key);

	/**
	 * Returns the value of this language key.
	 *
	 * @return the value of this language key
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this language key.
	 *
	 * @param value the value of this language key
	 */
	public void setValue(String value);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		de.unipotsdam.elis.language.model.LanguageKey languageKey);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.unipotsdam.elis.language.model.LanguageKey> toCacheModel();

	@Override
	public de.unipotsdam.elis.language.model.LanguageKey toEscapedModel();

	@Override
	public de.unipotsdam.elis.language.model.LanguageKey toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}