/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.unipotsdam.elis.language.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import de.unipotsdam.elis.language.service.persistence.LanguageKeyJournalArticlePK;

import java.io.Serializable;

/**
 * The base model interface for the LanguageKeyJournalArticle service. Represents a row in the &quot;Language_LanguageKeyJournalArticle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.unipotsdam.elis.language.model.impl.LanguageKeyJournalArticleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.unipotsdam.elis.language.model.impl.LanguageKeyJournalArticleImpl}.
 * </p>
 *
 * @author Matthias
 * @see LanguageKeyJournalArticle
 * @see de.unipotsdam.elis.language.model.impl.LanguageKeyJournalArticleImpl
 * @see de.unipotsdam.elis.language.model.impl.LanguageKeyJournalArticleModelImpl
 * @generated
 */
public interface LanguageKeyJournalArticleModel extends BaseModel<LanguageKeyJournalArticle> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a language key journal article model instance should use the {@link LanguageKeyJournalArticle} interface instead.
	 */

	/**
	 * Returns the primary key of this language key journal article.
	 *
	 * @return the primary key of this language key journal article
	 */
	public LanguageKeyJournalArticlePK getPrimaryKey();

	/**
	 * Sets the primary key of this language key journal article.
	 *
	 * @param primaryKey the primary key of this language key journal article
	 */
	public void setPrimaryKey(LanguageKeyJournalArticlePK primaryKey);

	/**
	 * Returns the key of this language key journal article.
	 *
	 * @return the key of this language key journal article
	 */
	@AutoEscape
	public String getKey();

	/**
	 * Sets the key of this language key journal article.
	 *
	 * @param key the key of this language key journal article
	 */
	public void setKey(String key);

	/**
	 * Returns the article ID of this language key journal article.
	 *
	 * @return the article ID of this language key journal article
	 */
	@AutoEscape
	public String getArticleId();

	/**
	 * Sets the article ID of this language key journal article.
	 *
	 * @param articleId the article ID of this language key journal article
	 */
	public void setArticleId(String articleId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		de.unipotsdam.elis.language.model.LanguageKeyJournalArticle languageKeyJournalArticle);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.unipotsdam.elis.language.model.LanguageKeyJournalArticle> toCacheModel();

	@Override
	public de.unipotsdam.elis.language.model.LanguageKeyJournalArticle toEscapedModel();

	@Override
	public de.unipotsdam.elis.language.model.LanguageKeyJournalArticle toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}